# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: josephcrowell.passage::lang.key.model

# Model Form Field configuration
form: $/josephcrowell/passage/models/key/fields.yaml

# Model Class name
modelClass: JosephCrowell\Passage\Models\Key

# Default redirect location
defaultRedirect: josephcrowell/passage/keys

# Create page
create:
    redirect: josephcrowell/passage/keys/update/:id
    redirectClose: josephcrowell/passage/keys

# Update page
update:
    redirect: josephcrowell/passage/keys
    redirectClose: josephcrowell/passage/keys

# Preview page
preview: