# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: josephcrowell.passage::lang.variance.model

# Model Form Field configuration
form: $/josephcrowell/passage/models/variance/fields.yaml

# Model Class name
modelClass: JosephCrowell\Passage\Models\Variance

# Default redirect location
defaultRedirect: josephcrowell/passage/variances

# Create page
create:
    redirect: josephcrowell/passage/variances/update/:id
    redirectClose: josephcrowell/passage/variances

# Update page
update:
    redirect: josephcrowell/passage/variances
    redirectClose: josephcrowell/passage/variances

# Preview page
preview:
