# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: josephcrowell.passage::lang.permission.model

# Model Form Field configuration
form: $/josephcrowell/passage/models/permission/fields.yaml

# Model Class name
modelClass: JosephCrowell\Passage\Models\Permission

# Default redirect location
defaultRedirect: josephcrowell/passage/permissions

# Create page
create:
    redirect: josephcrowell/passage/permissions/update/:id
    redirectClose: josephcrowell/passage/permissions

# Update page
update:
    redirect: josephcrowell/passage/permissions
    redirectClose: josephcrowell/passage/permissions

# Preview page
preview: