# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: $/josephcrowell/passage/models/permission/columns.yaml

# Model Class name
modelClass: JosephCrowell\Passage\Models\Permission

# List Title
title: josephcrowell.passage::lang.permissions_comp.page_title

# Link URL for each record
recordUrl: josephcrowell/passage/permissions/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 20

# Displays the list column set up button
showSetup: true

# Displays the sorting link on each column
showSorting: true

# Default sorting column
defaultSort:
    column: name
    direction: asc

# Display checkboxes next to each record
# showCheckboxes: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt